### ISSUE TITLE
Design initial layout and chatbot interface

### ISSUE THREAD

**Issue by dotnize** [mugnavo/varo.dev#3]
Typical chat app UI? Pretty much just like LLM UIs like chatgpt.com

![image](https://github.com/user-attachments/assets/2d4d3293-f0f0-48c5-afe3-c2958c3c386a)

- In the sidebar, our main chatbot convo should be pinned at the top.
- Convos for successful user/project matches can be below.

#### Considerations:

- Should we keep chat history (or previous conversations) for our main chatbot?
- Prioritize mobile screen sizes. Make use of [Vant UI](https://vant.pro/vant/) components.

**Comment by JoshCunningHum** [comment]
Keeping the chat history for the main chatbot could create clutter in the sidebar, I suggest we only keep the current session (stored in some store) and when the page closes, the data is deleted. If you want to save the data tho (for continuing where you left off using the app) then a single table is needed, but only store probably the last 10 interactions

**Comment by dotnize** [comment]
> I suggest we only keep the current session (stored in some store)

kani nalang sa for now. maybe soon after the hackathon nalang nang uban ideas

> only store probably the last 10 interactions

kani sad pwede buhaton ron para tipid tokens sa gemini. max 10 interactions even for current session

**Comment by haerld** [comment]
I'll be requiring a wireframe for this one @dotnize
